REQUIRED_H3_RUNTIME_NODES = {
    "BasicScheduler",
    "CLIPLoader",
    "CreateVideo",
    "MMH3LatentUpscaleWithModelParams",
    "MMH3SpatialSplitParams",
    "MMH3TemporalSplitParams",
    "MMH3UltimateUpscale",
    "MiniMaxH3ReferenceToVideo",
    "MiniMaxH3TurboLoRA",
    "MiniMaxH3TurboSampler",
    "MinimaxH3LatentUpscaler3D",
    "SamplerCustomAdvanced",
    "SaveVideo",
    "UNETLoader",
    "VAEDecode",
    "VAEDecodeAudio",
}
